### ISSUE TITLE
Can't exclude Routes.* for coverage

### ISSUE THREAD

**Issue by tianhao-au** [scoverage/sbt-scoverage#136]
I used sbt-scoverage for play app and I used the following config to exclude both Reverse and Routes generated file.

coverageExcludedPackages := "<empty>;Reverse._;Routes._;"

However this can only exclude generated Reverse scala files and can't exclude Routes files. Even I use the following script, it does the same

coverageExcludedPackages := "<empty>;Routes.*;"

Anyone knows what should I do?

Thanks.

**Comment by ysihaoy** [comment]
Anyone knows the fix? It's very frustrating.

**Comment by alradur** [comment]
The Routes classes are defined in package routes. In order to exclude them you either need to change the regex to """..*Routes.*;""" or """router.Routes.*;""" to only exclude Routes classes in package routes.

As far as i know the Reverse classes are generated for controllers only. So you can also limit the rule for Reverse classes to package controllers.

The following works for us in play applications:
coverageExcludedPackages := """controllers\..*Reverse.*;router.Routes.*;"""

**Comment by rethab** [comment]
Thanks, this worked for me.

**Comment by ckipp01** [comment]
This looks to be solved. I'll go ahead and close.
