### ISSUE TITLE
coverageAggregate dropping Tests or IntegrationTests depending on ordering

### ISSUE THREAD

**Issue by fommil** [scoverage/sbt-scoverage#142]
example of failure (note, use the branch at ensime/ensime-server#1090 until merged):

```
git clone git@github.com:ensime/ensime-server.git
cd ensime-server
# add your locally published version of sbt-coveralls to project/plugins.sbt
sbt gen-ensime
sbt coverage test it:test
sbt coverageAggregate
```

open the report and see that the `org.ensime.api` module has 0% coverage (click through) but if the `test` and `it:test` phases are broken out separately the result is different.

**Comment by andrestc** [comment]
I think thats happening because the report generated from it:test is overwriting the first one, generated by test. I stumbled open the same issue.

Maybe provide a way to name the report file depending on the type of the test? So we can (or not) merge it on the end.

**Comment by ScalaWilliam** [comment]
:+1: experiencing this issue as well, real coverage is much higher than that :-)

**Comment by s-nel** [comment]
The underlying issue is that code from your main codebase `src/main` is recompiled during `it:test` with instrumentation enabled. When coverage is enabled, every time code from `src/main` is compiled with the instrumentation plugin both the instrumentation data, and the measurement data is deleted. For me this is because I was using scalariform plugin. At the beginning of `it:test` task scalariform runs and it thinks that a bunch of classes in `src/main` changed. It then recompiles those files and blows away the coverage data.

Here's the log output:

```
[info] Compiling 65 Scala sources and 1 Java source to /xxx/target/scala-2.11/classes...
[info] [info] Cleaning datadir [/xxx/target/scala-2.11/scoverage-data]
[info] [info] Beginning coverage instrumentation
[info] [info] Instrumentation completed [1477 statements]
[info] [info] Wrote instrumentation file [/xxx/target/scala-2.11/scoverage-data/scoverage.coverage.xml]
[info] [info] Will write measurement data to [/xxx/target/scala-2.11/scoverage-data]
```

Then tests are run. Then, when the `it:test` task starts, scalariform runs again, and code form `src/main` is recompiled:

```
[info] Formatting 23 Scala sources {file:/xxx/}root(compile) ...
[info] Reformatted 23 Scala sources {file:/xxx/}root(compile).
[info] Compiling 23 Scala sources and 1 Java source to /xxx/target/scala-2.11/classes...
[info] [info] Cleaning datadir [/xxx/target/scala-2.11/scoverage-data]
[info] [info] Beginning coverage instrumentation
[info] [info] Instrumentation completed [0 statements]
[info] [info] Wrote instrumentation file [/xxx/target/scala-2.11/scoverage-data/scoverage.coverage.xml]
[info] [info] Will write measurement data to [/xxx/target/scala-2.11/scoverage-data]
```

I'm not sure why `0 statements` in the second compilation, but by disabling scalariform, I was able to produce a combined report. Also it's unnecessary to use `coverageAggregate` unless you have multiple projects. `coverageReport` is the correct task to run.

`sbt ";clean;coverage;test;it:test;coverageReport"`

**Comment by RomanIakovlev** [comment]
Is this now closed because it's fixed, or for some other reason?

**Comment by mwz** [comment]
@fommil is leaving Scala with a bang and closing all of his issues 😄

**Comment by fommil** [comment]
fommil is cleaning up his github history, don't make a mountain out of a molehill :wink: Please recreate if you want to continue to track this.
