### ISSUE TITLE
Coverage reports not generated in 1.3.5 plugin

### ISSUE THREAD

**Issue by natemurthy** [scoverage/sbt-scoverage#161]
I noticed that when using sbt-scoverage plugin 1.3.5 that coverage reports are no longer generated using the command

```
sbt clean coverage test
```

I have to run a separate command now to generate the report

```
sbt coverageReport
```

whereas in earlier versions of the plugin (e.g. 1.10) I could just run the first command and also get the coverage report at the end of my tests. What was the motivation for doing this? I see no difference now in running `sbt clean test` and `sbt clean coverage test` in the newer release of the plugin.

I have SBT 0.13.9 with Scala 2.11.7

**Comment by hamiltondfp** [comment]
Running `sbt clean coverage test` will generate the scoverage-data under target/scala-[version]/

Running `sbt coverageReport` will create the the coverage-report and scoverage-report data in the same directory after you have ran `sbt clean coverage test`.

So running `sbt clean coverage test` is still required, but you are correct that running `sbt coverageReport` was not required in previous versions. I too would be interested to know if this is by design and if so I'm interested in knowing the advantage.

**Comment by natemurthy** [comment]
Yes,

> I too would be interested to know if this is by design and if so I'm interested in knowing the advantage.

I am in the same boat as @hamiltondfp

**Comment by ckipp01** [comment]
Seeing that this is quite old and there are newer versions available, I'm going to go ahead and close.
