### ISSUE TITLE
Produce output in a different location

### ISSUE THREAD

**Issue by dblock** [scoverage/sbt-scoverage#202]
With Circle-CI I am currently doing something fairly unnatural to find the test coverage output and put it in a place that gets picked up and saved. Any better suggestions? Maybe an option to output reports directly into `$CIRCLE_ARTIFACTS`?

```
test:
  post:
    - sbt coverageReport
    - find target -name scoverage-report -exec cp -r {} $CIRCLE_ARTIFACTS \;
```

**Comment by dblock** [comment]
Related, https://github.com/circleci/circleci-docs/pull/415, comment on any improvements to the docs please.

**Comment by gslowikowski** [comment]
Hi

`find ...` is general command, good for CircleCI documentation, but it works only with single-module builds, without cross-scala build. In multi-module or cross-builded project it will overwrite report files.

In single-module build for specified Scala version you know the location of `scoverage-report` directory. It's `target/scala-${scalaBinaryVersion}/scoverage-report`, no need to use `find`.

In multi-module with one Scala version you can aggregate reports -`sbt coverageAggregate` and proceed as described above.

If you have multiple modules and you don't want to aggregate or you build for many Scala versions you have to copy directories from each module/Scala version to separate subdirectory of `$CIRCLE_ARTIFACTS`.

Additionally, if you want to browse HTML report directly on CircleCI site, that's all.
But if you want to download the reports and publish them somewhere else, you can zip `scoverage-report` directory. This functionality was added as part of TeamCity support issue #140, but maybe it would be good to add more general setting for controlling zip creation.

I've recently tested Scala build with Scoverage with CircleCI (check [configuration file](https://github.com/gslowikowski/scala/blob/2.11.x-scoverage/circle.yml)) . This is multi-module build. I gathered Scoverage reports both separated and aggregated. In both cases with zipped content. See [produced artifacts](https://circleci.com/gh/gslowikowski/scala/65#artifacts/containers/0). I hope this link is accessible.

We can discuss here, what can be improved in Scoverage and in CircleCI documentation.

**Comment by dblock** [comment]
I couldn't find any circle-ci doc for getting the scala binary version, `${scalaBinaryVersion}`, doesn't seem to exist or does it? Where did you find this? I'm happy to test.

**Comment by gslowikowski** [comment]
You get me wrong. There is no such variable in CircleCI. Target directories in SBT build are e.g. `target/scala-2.10` for Scala 2.10.x or `target/scala-2.11` for Scala 2.11.x. Yoy have to write it something in the documentation :)

**Comment by dblock** [comment]
Right, I was hoping I could programmatically find out what the version of scala is and use it there, I guess everyone "knows" what they use and could just hard-code it.

**Comment by gslowikowski** [comment]
I've created a [simple project](https://github.com/gslowikowski/sbt-multimodule-circleci-test) to illustrate, what I wrote before. Build artifacts tab is [here](https://circleci.com/gh/gslowikowski/sbt-multimodule-circleci-test/2#artifacts/containers/0).

Can you simplify `test/post` section of [circle.yml](https://github.com/gslowikowski/sbt-multimodule-circleci-test/blob/master/circle.yml) file?
If CircleCI would support matrix build (like Travis), it would make life a little bit easier, but it doesn't.

Additionally, I found some errors in your circleci/circleci-docs#415 PR:
- "In Scala 2.x ..." - there is no Scala 2.x
- `sbt-coverage` should be `sbt-scoverage` (missing `s` letter)
- use latest `1.5.0` version of the plugin (`1.3.5` is old)
- what is `sbt 'set test in assembly := {}' assembly` command for? is it from your project? this is not universal so shouldn't be here IMO

What about cross-Scala builds (commands with `+` prefix)?

Your PR fits single-module builds. There should be (separate?) information about multi-module build, with information about optional aggregation step `sbt coverageAggregate`.

I don't know, how it all should be best written, because I'm not native English speaker, so I leave it to you.

**Comment by dblock** [comment]
Thanks for your feedback and for bearing with me, I have close to no scala experience :)

With your suggested changes `sbt coverage test:compile` in `dependencies` will compile the project, then `sbt coverage test` in `test` will compile it again? Why would I want to do that?

The `sbt 'set test in assembly := {}' assembly` builds the assembly package, but skips running tests. That's cause we just ran them. 

For my general education, is compiled output with/without coverage any different? I assume coverage is injected somehow, so I would imagine we're getting the same code. So I want only 1 compilation pass, 1 test run with coverage and 1 assembly package. This was the only way I was able to achieve it.

**Comment by dblock** [comment]
Regarding +coverage, it seems like this is fairly specialized for those running builds against multiple versions of scala. Do we really want that as part of the default doc?

**Comment by gslowikowski** [comment]
I've created [another example project](https://github.com/gslowikowski/sbt-simple-circleci-test) - simple one this time - single module, built for one Scala version only.

CircleCI configuration files for both projects are very different.

**Comment by dblock** [comment]
I've heavily edited the circle-ci doc in https://github.com/circleci/circleci-docs/pull/424, lets take the discussion there wrt the actual commands to run and leave this issue as a feature request to specify where coverage output goes?

**Comment by dblock** [comment]
@gslowikowski mind checking out https://github.com/circleci/circleci-docs/pull/424? Thanks.

**Comment by ckipp01** [comment]
I'm going to go ahead and close seeing that this did result in a pr. Please open back up if there is something else missing or something is unclear.
