### ISSUE TITLE
Not a valid command: coverageReport

### ISSUE THREAD

**Issue by firegate666** [scoverage/sbt-scoverage#209]
I have an issue running the coverage report on my jenkins. It works fine locally but breaks on jenkins. All other jenkins sbt commands work fine

These are my commands executed:

- clean compile coverage test scalastyle cpd
- coverageReport

sbt 0.13.11

```
[info] [info] Beginning coverage instrumentation
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [warn] Could not instrument [EmptyTree$/null]. No pos.
[info] [info] Instrumentation completed [26560 statements]
[info] [info] Wrote instrumentation file [/var/lib/jenkins/workspace/hero-backend-test/backend/target/scala-2.11/scoverage-data/scoverage.coverage.xml]
[info] [info] Will write measurement data to [/var/lib/jenkins/workspace/hero-backend-test/backend/target/scala-2.11/scoverage-data]
[info] Defining {.}/*:coverageEnabled
[info] The new value will be used by no settings or tasks.
[info] Reapplying settings...
[hero-backend-test] $ /var/lib/jenkins/tools/hudson.model.JDK/Java_8/bin/java -Dsbt.log.noformat=true -jar /var/lib/jenkins/tools/org.jvnet.hudson.plugins.SbtPluginBuilder_SbtInstallation/sbt_0.13.11/bin/sbt-launch.jar coverageReport
[info] Set current project to hero-backend-test (in build file:/var/lib/jenkins/workspace/hero-backend-test/)
[error] Not a valid command: coverageReport
[error] Not a valid project ID: coverageReport
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: coverageReport (similar: compilerReporter)
[error] coverageReport
[error]               ^
```

**Comment by gslowikowski** [comment]
What's your Scala and Scoverage plugin version? Set log level to debug and see if there is something interesting in the logs. It's hard to guess what's wrong without a possibility to reproduce the problem locally.

**Comment by japneet-sahni** [comment]
@gslowikowski : Even I am facing the same issue. I have following versions:

sbt : 1.1.2
scala : 2.12
SonarQube : 6.7.2
I have added build.properties and plugins.sbt with below line in project folder.
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")

jenkins Console Output

Injecting SonarQube environment variables using the configuration: SonarQube-6.7
[code_coverage] $ java -Dsbt.log.noformat=true -jar /var/lib/jenkins/tools/org.jvnet.hudson.plugins.SbtPluginBuilder_SbtInstallation/1.1.2/bin/sbt-launch.jar clean package test coverageReport
[warn] No sbt.version set in project/build.properties, base directory: /var/lib/jenkins/workspace/code_coverage
[info] Set current project to code_coverage (in build file:/var/lib/jenkins/workspace/code_coverage/)
[success] Total time: 1 s, completed Apr 10, 2018 11:49:59 AM
[info] Updating ...
[info] Done updating.
[info] Packaging /var/lib/jenkins/workspace/code_coverage/target/scala-2.12/code_coverage_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[success] Total time: 1 s, completed Apr 10, 2018 11:50:01 AM
[success] Total time: 0 s, completed Apr 10, 2018 11:50:01 AM
[error] Not a valid command: coverageReport
[error] Not a valid project ID: coverageReport (similar: code_coverage)
[error] Expected ':'
[error] Not a valid key: coverageReport (similar: compilerReporter)
[error] coverageReport
[error]               ^
Build step 'Build using sbt' changed build result to FAILURE
Build step 'Build using sbt' marked build as failure
Publishing Scoverage XML and HTML report ...
ERROR: Step ‘Publish Scoverage Report’ aborted due to exception: 
java.io.IOException: /var/lib/jenkins/workspace/code_coverage/target/scala-2.12/scoverage-report not exists at org.jenkinsci.plugins.scoverage.ScoveragePublisher.copyReport(ScoveragePublisher.java:114)

**Comment by ckipp01** [comment]
So the initial issue in here has actually been addressed upstream. As for the command not found, it's very hard to tell without an exact reproduction. Since this is also quite old I'm going to go ahead and close, but please feel free to open back up if you are still having issues.
