### ISSUE TITLE
Position Error: Enclosing tree [35043] does not include tree [35042]

### ISSUE THREAD

**Issue by refried** [scoverage/sbt-scoverage#210]
~Trying to add sbt-scoverage and encountered this error during test compilation.~

~I know this isn't  not much to go on, but in a 10kloc project I'm not sure how to go about creating a minimal example.~

~How can I go about diagnosing or finding relevant information to report?~

~I'm using specs2 v3.8.6; I thought that might be relevant.~

~I really want coverage highlighting :-)~

Edit: See below.

**Comment by gslowikowski** [comment]
What are your Scala and Scoverage plugin versions?

**Comment by refried** [comment]
Hi, they are 2.11.8 and 1.5.0.

**Comment by refried** [comment]
I was able to make a small example that reproduces the error:
https://gist.github.com/refried/0f1411cd88b1cfcd2141215b9fa1baa1

**Comment by refried** [comment]
Even simpler:
```
object Test1 { 1 -> 2 }       // ok
object Test2 { 1.->(2) }      // ok
object Test3 { 1.->[Int](2) } // ok
object Test4 { 1 ->[Int] 2 }  // fails
```

```
object Test1 { List(1,2).foreach(println) }       // ok
object Test2 { List(1,2) foreach println }        // ok
object Test3 { List(1,2).foreach[Unit](println) } // ok
object Test4 { List(1,2) foreach[Unit] println }  // fails
```

**Comment by refried** [comment]
Note:
```
// $COVERAGE-OFF$
// $COVERAGE-ON$
```
around the offending area doesn't help; maybe I'm doing it wrong though?

**Comment by gslowikowski** [comment]
Your first example doesn't compile for me.

The second one is nice. The error is thrown from validation phase, before the compilation starts. The reason is [-Yrangepos option](https://github.com/scoverage/sbt-scoverage#highlighting) added to `scalacOptions` by default (see it in [the code](https://github.com/scoverage/sbt-scoverage/blob/v1.5.0/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L83)).

When you add `coverageHighlighting := false` setting, compilation succeeds.

Another test - when you add `scalacOptions in(Compile, compile) += "-Yrangepos"` setting, compilation fails even without coverage (`sbt clean compile`).

[Highlighting](https://github.com/scoverage/sbt-scoverage#highlighting) documentation paragraph should be updated. As you found it, some cases cause problems even with latest 2.11.x and 2.12.x Scala versions.

So, the only solution in your case is to turn off `coverageHighlighting`.

**Comment by refried** [comment]
Ah, I understand now that this issue stems from `-Yrangepos` and not scoverage.  Thank you.

So the possible solutions are:
1. avoid `-Yrangepos` by disabling `coverageHighlighting`
2. use one of the 3 "ok" syntaxes above that don't fail with `-Yrangepos`
3. file a scalac bug and wait for a fix.

I don't want (1), so I went with (2), and I will look into (3).
