### ISSUE TITLE
Error on executing test with scoverage on sbt 1.0.0

### ISSUE THREAD

**Issue by albertoadami** [scoverage/sbt-scoverage#250]
Hi,
I'm getting some problems on using scoverage on sbt project.
The sbt version used is 1.0.0 and the scala version is 2.12.4.

I've added the scoverage plugin on plugins.sbt with addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1").

When i try to type sbt clean coverage test i get the following error:

[error] java.lang.Exception: Fatal: scalac-scoverage-plugin not in libraryDependencies
[error] 	at scoverage.ScoverageSbtPlugin$.$anonfun$scalacSettings$1(ScoverageSbtPlugin.scala:75)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (compile:compile::scalacOptions) java.lang.Exception: Fatal: scalac-scoverage-plugin not in libraryDependencies
[error] Total time: 3 s, completed 18-gen-2018 0.20.21

**Comment by gslowikowski** [comment]
Hi @albertoadami 

Check, if you don't have `libraryDependencies := ...` somewhere in your build, instead of `libraryDependencies ++= ...`.

Scoverage [adds some dependencies](https://github.com/scoverage/sbt-scoverage/blob/v1.5.1/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L55-L66) to `libraryDependencies`.
If you (or one of other plugins your build uses) override `libraryDependencies` (with `:=` assignment), such exception will be thrown.

See [this comment](https://github.com/scoverage/scalac-scoverage-plugin/issues/102#issuecomment-74478401) in another issue.

**Comment by albertoadami** [comment]
Hi @gslowikowski 

using libraryDependencies ++= ... fix the problem.

Thank you.
