### ISSUE TITLE
Build failure with Scala 2.13.1

### ISSUE THREAD

**Issue by plokhotnyuk** [scoverage/sbt-scoverage#295]
https://travis-ci.org/plokhotnyuk/expression-evaluator/jobs/586472890

```
error] ## Exception when compiling 1 sources to /Users/travis/build/plokhotnyuk/expression-evaluator/target/scala-2.13/classes
[error] java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
[error] scoverage.ScoverageInstrumentationComponent$$anon$1.run(plugin.scala:119)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
...
```

https://travis-ci.org/plokhotnyuk/jsoniter-scala/jobs/586468216

```
[error] ## Exception when compiling 4 sources to /Users/travis/build/plokhotnyuk/jsoniter-scala/jsoniter-scala-core/target/scala-2.13/classes
[error] java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
[error] scoverage.ScoverageInstrumentationComponent$$anon$1.run(plugin.scala:119)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
```

**Comment by ILLKO** [comment]
Needs scalac-scoverage-plugin with this pull request merged https://github.com/scoverage/scalac-scoverage-plugin/pull/279

**Comment by lrytz** [comment]
https://github.com/scoverage/scalac-scoverage-plugin/pull/279 allows compiling the plugin against 2.13.1 (and it remains compileable with older Scala versions).

The runtime failure is because the scala-compiler.jar of 2.13.1 is **not** binary compatible with the scala-compiler.jar of 2.13.0. This is **not** a bug, we only guarantee binary compatibility for the library. This means that compiler plugins have to be fully cross-versioned.

Concretely, [`scalac-scoverage-plugin_2.13:1.4.1`](https://search.maven.org/artifact/com.twitter.scoverage/scalac-scoverage-plugin_2.13/1.4.1/jar) should not exist, instead there should be `scalac-scoverage-plugin_2.13.0` and `scalac-scoverage-plugin_2.13.1`.

Note that this is true for all compiler plugins (see https://github.com/typelevel/kind-projector/issues/15 for example).

For reference, the changes to wartremover that were done by @xuwei-k to support full cross-versioning: https://github.com/wartremover/wartremover/compare/5c59c86008b4de9ddc6854a01e4340194dab3ccf...acc56b86b28c3135c43a7eef435fd299476ff82c

**Comment by Christewart** [comment]
Just a :+1: , i'm encourtering this failure when attempting to upgrade bitcoin-s to 2.13.1 https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/588220140#L352

**Comment by regis-leray** [comment]
I have the same issue with scala 2.13.1 and scoverage 1.6.0 
 
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

```
[error] java.lang.NoSuchMethodError: 'scala.tools.nsc.reporters.Reporter scala.tools.nsc.Global.reporter()'
[error] scoverage.ScoverageInstrumentationComponent$$anon$1.run(plugin.scala:119)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1614)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by nrinaudo** [comment]
I'm also struggling with this issue. If there anything I can do to help getting it resolved?

**Comment by leonardehrenfried** [comment]
I'm not a maintainer but I would guess that if you want to help, you can open a PR that adds full cross-compilation down to the minor version number, as suggested here: https://github.com/scoverage/sbt-scoverage/issues/295#issuecomment-533459449

Basically, this plugin is only cross-compiled for scala 2.13 when it actually needs to be compiled for 2.13.0 and 2.13.1. 

Usually this isn't a problem but there appears to be an API change between 2.13.0 and 2.13.1.

**Comment by nrinaudo** [comment]
There's another, quicker solution: the one that @olafurpg asked me to put together for `mdoc` in https://github.com/scalameta/mdoc/pull/196.

Instead of changing the publication mechanism and publishing artifacts for every single verion of scala, keep publishing global ones for 2.11, 2.12 and 2.13, but only make them compatible with the latest Scala version.

For example, if we were to do that to scoverage, the next version would only be tested against 2.11.12, 2.12.10 and 2.13.1.

With the current state of Scala, that would mean:
* compatible with 2.11.x for all x
* compatible with 2.12.x for all x
* compatible with 2.13.1, but not 2.13.0

If the reporter API stays stable from now on, problem sorted. If it doesn't, "just" fix the breakage and release a non-backwards compatible build for the latest versions.

I can absolutely have a go at that if you feel this would be an acceptable solution.

**Comment by leonardehrenfried** [comment]
Speaking as a user, this is a totally acceptable solution.

**Comment by nrinaudo** [comment]
I have a working proof of concept - it's really very little work.

Replace `2.13.0` by `2.13.1` in `scalac-scoverage-plugin`'s build file, and publish locally (`+publishLocal`).
This should publish version `1.4.1-SNAPSHOT`.

Load up whatever project you have that uses scoverage and 2.13.1, and set the appropriate property:
```
set every coverageScalacPluginVersion := "1.4.1-SNAPSHOT"
```

Done. You now have working code coverage.

The clean thing to do would be to publish `scalac-scoverage-plugin 1.4.1`, then update `sbt-scoverage` so that it defaults to `1.4.1` and not `1.4.0`, and publish that. You're done. It's two 1-line-diffs, with the caveat that you've lost support for 2.13.0.

Happy to submit the corresponding PRs, but I'd love to get approval from a project maintainer first that this is the way they want to go.

**Comment by nrinaudo** [comment]
PRs submitted:
- [scalac-scoverage-plugin](https://github.com/scoverage/sbt-scoverage/pull/299)
- [sbt-scoverage](https://github.com/scoverage/sbt-scoverage/pull/299)

Do let me know if there's anything else I can do to push this forward!

**Comment by polomarcus** [comment]
Just met this error, and finding this thread solved is beautiful

Merci @nrinaudo et @D-Roch :trophy:

**Comment by asavelyev01** [comment]
Just met this error with Scala `2.12.13`. Does it need a different fix?

**Comment by eugeniyk** [comment]
@asavelyev01 duplicate of #319
