### ISSUE TITLE
Is it possible to run with Bloop?

### ISSUE THREAD

**Issue by zzvara** [scoverage/sbt-scoverage#317]
Is it possible to used `sbt-scoverage` with Bloop? And if so, how?

Thanks!

**Comment by ckipp01** [comment]
@zzvara so it sort of depends what the end goal is. In general scoverage is just a compiler plugin, and yes, you can use compiler plugins via Bloop. However, if you're using sbt-scoverage, then it's probably just recommended to use sbt to run your coverage reports. Is there something specific you're trying to achieve with Bloop in this scenario? Ultimately this may be a better question for the compiler plugin instead of here.

**Comment by ckipp01** [comment]
If the above didn't answer your question well enough let me know if you'd like some more details.
