### ISSUE TITLE
org.scoverage library dependencies are explicitly declared

### ISSUE THREAD

**Issue by DutchDestroyer** [scoverage/sbt-scoverage#459]
After upgrading the sbt-scoverage plugin from version 1.9.3 to version 2.0.2 I received the following error when running my pipeline:

```
The following libraries are declared in libraryDependencies but are not needed for compilation:
[warn]  - "org.scoverage" %% "scalac-scoverage-domain" % "2.0.2"
[warn]  - "org.scoverage" %% "scalac-scoverage-reporter" % "2.0.2"
[warn]  - "org.scoverage" %% "scalac-scoverage-serializer" % "2.0.2"
```

I use the com.github.cb372 sbt-explicit-dependencies plugin version 0.2.15 to verify all dependencies are used.

**Comment by ckipp01** [comment]
Thanks for the report @DutchDestroyer. I'm not super familiar with how sbt-explicit-dependencies works but these dependencies are needed next to the compiler plugin or it will fail. For example you can see this with `domain` and `serializer` being used in [this file](https://github.com/scoverage/scalac-scoverage-plugin/blob/main/plugin/src/main/scala/scoverage/ScoveragePlugin.scala).

**Comment by martijnhoekstra** [comment]
These packages are being reported by sbt-explicit-dependencies as existing on the compile classpath of the project -- and then also get packaged along when releasing.

I have the initial impression that it's correct: `whatDependsOn org.scoverage scalac-scoverage-domain_2.12` reports nothing, which I think means it's there (or it would be an error) but not depended on by anything (or there would be output)

Is that enough for you to go on? Otherwise, I could check if any of these jars actually end up in the packed release when building with scoverage 2.0.2 enabled

**Comment by martijnhoekstra** [comment]
Thanks @ckipp01, I'll check our processes, and also check what exactly ends up where

**Comment by martijnhoekstra** [comment]
Looks like this is indeed the case. I do wonder why our CI never had issues with this before, but the artifacts indeed only show up in the classpath when I run coverage.
